# defining extra synthetic poses in the local frame tags
# translation in meters and rotation in degrees
random_poses:
  [
    {prob: 0.5, x: -0.2, y: 0.5, z: 0.0, angle_x: 0.0, angle_y: 0.0, angle_z: 0.0},
    {prob: 0.5, x: 0.2, y: -0.5, z: 0.0, angle_x: 0.0, angle_y: 0.0, angle_z: 180.0}
  ]
